web3py-ext/setup.py, web3py-ext/web3py_ext/example/account/account_update/1-legacy_account_key.py, web3py-ext/web3py_ext/extend.py, web3py-ext/web3py_ext/klaytn_account/instrumented_local_account.py, web3py-ext/web3py_ext/transaction/basic/account_update_transaction.py, web3py-ext/web3py_ext/transaction/basic/cancel_transaction.py, web3py-ext/web3py_ext/transaction/basic/chaindata_anchoring_transaction.py, web3py-ext/web3py_ext/transaction/basic/smart_contract_deploy_transaction.py, web3py-ext/web3py_ext/transaction/basic/smart_contract_execution_transaction.py, web3py-ext/web3py_ext/transaction/basic/value_transfer_transaction.py, web3py-ext/web3py_ext/transaction/basic/value_transfer_with_memo_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_account_update_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_cancel_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_chaindata_anchoring_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_smart_contract_execution_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_transaction.py, web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_with_memo_transaction.py
- sign_transaction bugfix caused by blob parameter
- eth_account v0.11.x compatibility fix
=> web3py-ext fix bugs

web3js-ext/example/accountKey/sign_tx_AccountKeyLegacy.js, web3js-ext/example/accountKey/sign_tx_AccountKeyPublic.js, web3js-ext/example/accountKey/sign_tx_AccountKeyRoleBased.js, web3js-ext/example/accountKey/sign_tx_AccountKeyWeightedMultiSig.js
update sign_tx_* examples
fix params for web3.klay.recoverFromTransaction
=> feat: update web3js-ext examples

ethers-ext/example/utils/keystoreV4_multi.js, ethers-ext/example/utils/keystoreV4_single.js, web3js-ext/example/utils/keystoreV3.js, web3js-ext/example/utils/keystoreV4_multi.js, web3js-ext/example/utils/keystoreV4_single.js
- Update ethers-ext Keystore V4 examples
- Add web3js-ext Keystore V4 examples
=> Add keystore V4 examples

js-ext-core/package.json
missed package for version up 1.0.1
=> feat: version js-ext-core up to 1.0.1

web3rpc/rpc-specs/components/schemas/common/Common.yaml, web3rpc/rpc-specs/paths/eth/transaction/call.yaml, web3rpc/rpc-specs/paths/eth/transaction/estimateGas.yaml, web3rpc/rpc-specs/paths/governance/getChainConfig.yaml, web3rpc/rpc-specs/paths/governance/getParams.yaml, web3rpc/rpc-specs/paths/governance/vote.yaml, web3rpc/rpc-specs/paths/kaia/configuration/getChainConfig.yaml, web3rpc/rpc-specs/paths/kaia/configuration/getParams.yaml, web3rpc/rpc-specs/paths/kaia/transaction/estimateGas.yaml, web3rpc/rpc-specs/paths/klay/configuration/getChainConfig.yaml, web3rpc/rpc-specs/paths/klay/configuration/getParams.yaml, web3rpc/rpc-specs/paths/klay/transaction/estimateGas.yaml
=> Revert "Revert "Feat/update rpc docs""

js-ext-core/src/field/account.ts
- make return type explicitly `WeightedPublicKey`
=> fix: type casting

ethers-ext/package.json, js-ext-core/package.json, web3j-ext/web3j-ext/build.gradle, web3js-ext/package.json, web3py-ext/setup.py
This version includes changes to util examples, bug fixes in js-ext-core:
1. https://github.com/kaiachain/kaia-sdk/pull/54
2. https://github.com/kaiachain/kaia-sdk/pull/53
=> feat: version up to 1.1.0

ethers-ext/package.json, web3j-ext/web3j-ext/build.gradle, web3js-ext/package.json, web3py-ext/setup.py
Changes:
- Intergrate js-ext-core unit conversion for ethers v6
- Added helpers
- `parseKaia`
- `parseKaiaUnits`
- `parseUnits`
=> feat: version up to 1.1.1

ethers-ext/package-lock.json, js-ext-core/package-lock.json
- Add package-lock.json for ethers-ext and js-ext-core to prevent future dependencies conflicts.
=> fix: add missing package lock

js-ext-core/package.json
Changes
1.  Support ESM.
2. Optimize for bundler.
=> feat: version up js-ext-core 1.2.0

web3rpc/sdk/client/javascript/javascript-config.yaml, web3rpc/sdk/client/javascript/openapi-test/test/klay/block/KlayGetBlockReceiptsApi.test.js, web3rpc/sdk/client/javascript/template/libraries/javascript/api.mustache
- Optimize web3rpc/javascript build size
- Remove unused models/classes
=> refactor: optimize web3rpc build size

.github/workflows/publish.yml
Update trigger for publishing web3rpc
=> feat: update publish script for web3rpc

ethers-ext/.mocharc.json, ethers-ext/package-lock.json, ethers-ext/package.json, ethers-ext/tsconfig.cjs.json, ethers-ext/tsconfig.json, web3js-ext/.mocharc.json, web3js-ext/package-lock.json, web3js-ext/package.json, web3js-ext/tsconfig.cjs.json, web3js-ext/tsconfig.json
- Support esm for web3js-ext and ethers-ext
=> feat: support esm for web3js-ext and ethers-ext

js-ext-core/misc/esm-package.json, js-ext-core/package-lock.json, js-ext-core/package.json, js-ext-core/tsconfig.json
add esm's package.json for supporting node < 22
=> feat: version up js-ext-core v2.0.3

.github/workflows/build-test.yml
Update tj-actions/changed-files version to 46
=> update changefile version

web3rpc/rpc-specs/components/schemas/common/Common.yaml
change `typeInt` type in TransactionReceipt.
=> fix: change typeInt from string to number in TransactionReceipt schema

web3js-ext/src/web3.ts
KaiaWeb3EthInterface type was not handled properly.
=> Fixed build error

ethers-ext/package.json, js-ext-core/package.json, viem-ext/package.json, web3j-ext/web3j-ext/build.gradle, web3js-ext/package.json, web3py-ext/setup.py
* As part of this release the inappbrowser issue in kaiawallet for ethers v5 is fixed.
=> Bumped all SDKs to 2.0.5

js-ext-core/README.md, js-ext-core/package.json
This upgrade is part of python library net version fix
=> Bumped js-ext-core to 2.0.9

ethers-ext/package.json, viem-ext/package.json, web3j-ext/web3j-ext/build.gradle, web3js-ext/package.json, web3py-ext/setup.py
Release for api documentation changes for GA and also python net version format issues
=> Bumped all versions to v2.0.9

ethers-ext/example/v5/browser-html/index.html, ethers-ext/example/v5/browser-html/main.js, ethers-ext/example/v5/browser-react/src/App.tsx, ethers-ext/example/v5/browser-react/src/components/AccountInfo.tsx, ethers-ext/example/v5/browser-react/src/components/Connect.tsx, ethers-ext/example/v5/browser-react/src/components/KlaytnFeeDelSC.tsx, ethers-ext/example/v5/browser-react/src/components/KlaytnSC.tsx, ethers-ext/example/v5/browser-react/src/components/LegacySC.tsx, ethers-ext/example/v5/browser-react/src/components/LegacyVT.tsx, ethers-ext/example/v5/browser-react/src/util.ts, ethers-ext/example/v6/browser-html/gasless.html, ethers-ext/example/v6/browser-html/index.html, ethers-ext/example/v6/browser-html/main.js, ethers-ext/example/v6/browser-react/src/App.tsx, ethers-ext/example/v6/browser-react/src/components/Connect.tsx, ethers-ext/example/v6/browser-react/src/components/KlaytnSC.tsx, ethers-ext/example/v6/browser-react/src/components/LegacySC.tsx, ethers-ext/example/v6/browser-react/src/components/LegacyVT.tsx, ethers-ext/example/v6/browser-react/src/util.ts, viem-ext/examples/browser-react/src/App.tsx, viem-ext/examples/browser-react/src/components/Connect.tsx, viem-ext/examples/browser-react/src/components/KlaytnFeeDelSC.tsx, viem-ext/examples/browser-react/src/components/KlaytnSC.tsx, viem-ext/examples/browser-react/src/components/LegacySC.tsx, viem-ext/examples/browser-react/src/components/LegacyVT.tsx, viem-ext/examples/browser-react/src/util.ts, web3js-ext/example/browser-html/index.html, web3js-ext/example/browser-html/main.js
=> fix: naming updates for baobab and kaikas
